//
//  HomePresentationTests-HomeApplicationMocks.generated.swift
//  HomeApplication
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import HomeApplication
@testable import Mockingbird
import Foundation
import Resolver
import RxSwift
import Swift

private let mkbGenericStaticMockContext = Mockingbird.GenericStaticMockContext()

// MARK: - Mocked GetArticlesSource
public final class GetArticlesSourceMock: HomeApplication.GetArticlesSource, Mockingbird.Mock {
  typealias MockingbirdSupertype = HomeApplication.GetArticlesSource
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "HomeApplication"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    GetArticlesSourceMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `articles`()
  public func `articles`() -> Observable<HomeApplication.ArticlesAuthorsLikes> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`articles`() -> Observable<HomeApplication.ArticlesAuthorsLikes>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<HomeApplication.ArticlesAuthorsLikes>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Observable<HomeApplication.ArticlesAuthorsLikes> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Observable<HomeApplication.ArticlesAuthorsLikes> = mkbObject.`articles`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Observable<HomeApplication.ArticlesAuthorsLikes>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `articles`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<HomeApplication.ArticlesAuthorsLikes>, Observable<HomeApplication.ArticlesAuthorsLikes>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<HomeApplication.ArticlesAuthorsLikes>, Observable<HomeApplication.ArticlesAuthorsLikes>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`articles`() -> Observable<HomeApplication.ArticlesAuthorsLikes>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<HomeApplication.ArticlesAuthorsLikes>).self)))
  }
}

/// Returns a concrete mock of `GetArticlesSource`.
public func mock(_ type: HomeApplication.GetArticlesSource.Protocol, file: StaticString = #file, line: UInt = #line) -> GetArticlesSourceMock {
  return GetArticlesSourceMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}

// MARK: - Mocked GetArticles
public final class GetArticlesMock: HomeApplication.GetArticles, Mockingbird.Mock {
  typealias MockingbirdSupertype = HomeApplication.GetArticles
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "HomeApplication"])

  public enum InitializerProxy {
    public static func initialize(__file: StaticString = #file, __line: UInt = #line) -> GetArticlesMock {
      let mock: GetArticlesMock = GetArticlesMock()
      mock.mockingbirdContext.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked mapper
  override public var `mapper`: HomeApplication.ArticlesMapper {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "mapper.getter", setterSelectorName: "mapper.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((HomeApplication.ArticlesMapper).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> HomeApplication.ArticlesMapper { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as HomeApplication.ArticlesMapper }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`mapper`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: HomeApplication.ArticlesMapper = mkbObject.`mapper`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (HomeApplication.ArticlesMapper).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "mapper.setter", setterSelectorName: "mapper.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (HomeApplication.ArticlesMapper) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`mapper` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`mapper` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getMapper() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> HomeApplication.ArticlesMapper, HomeApplication.ArticlesMapper> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> HomeApplication.ArticlesMapper, HomeApplication.ArticlesMapper>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "mapper.getter", setterSelectorName: "mapper.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((HomeApplication.ArticlesMapper).self)))
  }

  public func setMapper(_ newValue: @autoclosure () -> HomeApplication.ArticlesMapper) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (HomeApplication.ArticlesMapper) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (HomeApplication.ArticlesMapper) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "mapper.setter", setterSelectorName: "mapper.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked source
  override public var `source`: HomeApplication.GetArticlesSource {
    get {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "source.getter", setterSelectorName: "source.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((HomeApplication.GetArticlesSource).self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? () -> HomeApplication.GetArticlesSource { return mkbImpl() }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as HomeApplication.GetArticlesSource }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`source`
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: HomeApplication.GetArticlesSource = mkbObject.`source`
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (HomeApplication.GetArticlesSource).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
    set {
      return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "source.setter", setterSelectorName: "source.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))) {
        self.mockingbirdContext.recordInvocation($0)
        let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
        if let mkbImpl = mkbImpl as? (HomeApplication.GetArticlesSource) -> Void { return mkbImpl(newValue) }
        if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
        if let mkbImpl = mkbImpl as? (Any?) -> Any { return Mockingbird.dynamicCast(mkbImpl(newValue as Any?)) as Void }
        if let mkbImpl = mkbImpl as? () -> Any { return Mockingbird.dynamicCast(mkbImpl()) as Void }
        for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
          switch mkbTargetBox.target {
          case .super:
            return super.`source` = newValue
          case .object(let mkbObject):
            guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
            let mkbValue: Void = mkbObject.`source` = newValue
            self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
            return mkbValue
          }
        }
        if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
        self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
      }
    }
  }

  public func getSource() -> Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> HomeApplication.GetArticlesSource, HomeApplication.GetArticlesSource> {
    return Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> HomeApplication.GetArticlesSource, HomeApplication.GetArticlesSource>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "source.getter", setterSelectorName: "source.setter", selectorType: Mockingbird.SelectorType.getter, arguments: [], returnType: Swift.ObjectIdentifier((HomeApplication.GetArticlesSource).self)))
  }

  public func setSource(_ newValue: @autoclosure () -> HomeApplication.GetArticlesSource) -> Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (HomeApplication.GetArticlesSource) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.PropertySetterDeclaration, (HomeApplication.GetArticlesSource) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "source.setter", setterSelectorName: "source.setter", selectorType: Mockingbird.SelectorType.setter, arguments: [Mockingbird.resolve(newValue)], returnType: Swift.ObjectIdentifier(Void.self)))
  }

  // MARK: Mocked `articles`()
  public override func `articles`() -> Observable<[HomeApplication.Article]> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`articles`() -> Observable<[HomeApplication.Article]>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<[HomeApplication.Article]>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? () -> Observable<[HomeApplication.Article]> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          return super.`articles`()
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Observable<[HomeApplication.Article]> = mkbObject.`articles`()
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Observable<[HomeApplication.Article]>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `articles`() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<[HomeApplication.Article]>, Observable<[HomeApplication.Article]>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Observable<[HomeApplication.Article]>, Observable<[HomeApplication.Article]>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`articles`() -> Observable<[HomeApplication.Article]>", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Observable<[HomeApplication.Article]>).self)))
  }

  // MARK: Mocked init()
  public required override init() {
    super.init()
    self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "init()", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }

  public func initialize() -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, () -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "init()", selectorType: Mockingbird.SelectorType.method, arguments: [], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns an abstract mock which should be initialized using `mock(GetArticles.self).initialize(…)`.
public func mock(_ type: HomeApplication.GetArticles.Type, file: StaticString = #file, line: UInt = #line) -> GetArticlesMock.InitializerProxy.Type {
  return GetArticlesMock.InitializerProxy.self
}

// MARK: - Mocked LikeArticleSource
public final class LikeArticleSourceMock: HomeApplication.LikeArticleSource, Mockingbird.Mock {
  typealias MockingbirdSupertype = HomeApplication.LikeArticleSource
  public static let mockingbirdContext = Mockingbird.Context()
  public let mockingbirdContext = Mockingbird.Context(["generator_version": "0.20.0", "module_name": "HomeApplication"])

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    self.mockingbirdContext.sourceLocation = sourceLocation
    LikeArticleSourceMock.mockingbirdContext.sourceLocation = sourceLocation
  }

  // MARK: Mocked `findArticle`(`id`: String)
  public func `findArticle`(`id`: String) -> Observable<HomeApplication.ArticlesAuthorsLikes> {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`findArticle`(`id`: String) -> Observable<HomeApplication.ArticlesAuthorsLikes>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`id`)], returnType: Swift.ObjectIdentifier((Observable<HomeApplication.ArticlesAuthorsLikes>).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (String) -> Observable<HomeApplication.ArticlesAuthorsLikes> { return mkbImpl(`id`) }
      if let mkbImpl = mkbImpl as? () -> Observable<HomeApplication.ArticlesAuthorsLikes> { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Observable<HomeApplication.ArticlesAuthorsLikes> = mkbObject.`findArticle`(id: `id`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Observable<HomeApplication.ArticlesAuthorsLikes>).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `findArticle`(`id`: @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String) -> Observable<HomeApplication.ArticlesAuthorsLikes>, Observable<HomeApplication.ArticlesAuthorsLikes>> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (String) -> Observable<HomeApplication.ArticlesAuthorsLikes>, Observable<HomeApplication.ArticlesAuthorsLikes>>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`findArticle`(`id`: String) -> Observable<HomeApplication.ArticlesAuthorsLikes>", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`id`)], returnType: Swift.ObjectIdentifier((Observable<HomeApplication.ArticlesAuthorsLikes>).self)))
  }

  // MARK: Mocked `updateArticle`(`articlePlain`: HomeApplication.ArticlePlain)
  public func `updateArticle`(`articlePlain`: HomeApplication.ArticlePlain) -> Void {
    return self.mockingbirdContext.mocking.didInvoke(Mockingbird.SwiftInvocation(selectorName: "`updateArticle`(`articlePlain`: HomeApplication.ArticlePlain) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.ArgumentMatcher(`articlePlain`)], returnType: Swift.ObjectIdentifier((Void).self))) {
      self.mockingbirdContext.recordInvocation($0)
      let mkbImpl = self.mockingbirdContext.stubbing.implementation(for: $0)
      if let mkbImpl = mkbImpl as? (HomeApplication.ArticlePlain) -> Void { return mkbImpl(`articlePlain`) }
      if let mkbImpl = mkbImpl as? () -> Void { return mkbImpl() }
      for mkbTargetBox in self.mockingbirdContext.proxy.targets(for: $0) {
        switch mkbTargetBox.target {
        case .super:
          break
        case .object(let mkbObject):
          guard var mkbObject = mkbObject as? MockingbirdSupertype else { break }
          let mkbValue: Void = mkbObject.`updateArticle`(articlePlain: `articlePlain`)
          self.mockingbirdContext.proxy.updateTarget(&mkbObject, in: mkbTargetBox)
          return mkbValue
        }
      }
      if let mkbValue = self.mockingbirdContext.stubbing.defaultValueProvider.value.provideValue(for: (Void).self) { return mkbValue }
      self.mockingbirdContext.stubbing.failTest(for: $0, at: self.mockingbirdContext.sourceLocation)
    }
  }

  public func `updateArticle`(`articlePlain`: @autoclosure () -> HomeApplication.ArticlePlain) -> Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (HomeApplication.ArticlePlain) -> Void, Void> {
    return Mockingbird.Mockable<Mockingbird.FunctionDeclaration, (HomeApplication.ArticlePlain) -> Void, Void>(context: self.mockingbirdContext, invocation: Mockingbird.SwiftInvocation(selectorName: "`updateArticle`(`articlePlain`: HomeApplication.ArticlePlain) -> Void", selectorType: Mockingbird.SelectorType.method, arguments: [Mockingbird.resolve(`articlePlain`)], returnType: Swift.ObjectIdentifier((Void).self)))
  }
}

/// Returns a concrete mock of `LikeArticleSource`.
public func mock(_ type: HomeApplication.LikeArticleSource.Protocol, file: StaticString = #file, line: UInt = #line) -> LikeArticleSourceMock {
  return LikeArticleSourceMock(sourceLocation: Mockingbird.SourceLocation(file, line))
}
