//
//  HomePresentationTests-HomePresentationMocks.generated.swift
//  HomePresentation
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

@testable import HomePresentation
@testable import Mockingbird
import Foundation
import HomeApplication
import Resolver
import RxSwift
import Swift

// No mocks used in 'HomePresentationTests'. Mockingbird is configured to only generate mocks for
// types that are explicitly initialized in your tests with `mock(SomeType.self)`. For more
// information, see 'Thunk Pruning' in the README.
